projectMiWeb/main/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('post/<int:post_id>/', views.show_post, name='post'),
    path('category/<slug:cat_slug>/', views.show_category, name='category'),
]

projectMiWeb/projectMiWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projectMiWeb/main/models.py
from django.db import models
from django.urls import reverse


class Posts(models.Model):
    cat = models.ForeignKey('Category', on_delete=models.CASCADE)
    slug = models.SlugField(max_length=250, unique=True, db_index=True)
    date_posted = models.DateField()
    description = models.TextField()
    file = models.FileField(upload_to='files/', blank=True)

    def __str__(self):
        return f"{self.cat}{self.pk}"

    class Meta:
        verbose_name = 'Дом. задание'
        verbose_name_plural = 'Дом. задания'

    def get_absolute_url(self):
        return reverse('post',kwargs={'post_id': self.pk})


class Category(models.Model):
    name = models.CharField(max_length=50, db_index=True)
    slug = models.SlugField(max_length=250, unique=True, db_index=True)

    class Meta:
        verbose_name = 'Предмет'
        verbose_name_plural = 'Предметы'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category',kwargs={'cat_slug': self.slug})

projectMiWeb/main/forms.py
from django.forms import ModelForm,DateInput, Textarea, Select, FileInput
from .models import Posts, Category


class PostsForm(ModelForm):
    class Meta:
        model = Posts
        fields = ['description','cat','date_posted', 'file']

        widgets = {
            "description": Textarea(attrs={'class': 'form-control'}),
            "cat": Select(attrs={'class': 'form-control'}),
            "date_posted": DateInput(attrs={'class': 'form-control','type':'date'}),
            "file": FileInput(attrs={'class': 'form-control', 'type': 'file'})

        }

projectMiWeb/main/views.py
from django.contrib.auth.views import LoginView
from django.http import Http404
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404

from .forms import PostsForm
from .models import Posts, Category


def home_page(request):
    return render(request,'main/index.html')




def show_post(request, post_id):
    post = get_object_or_404(Posts, pk=post_id)
    return render(request,'main/post_detail.html',{'post_id': post_id,'post': post})


def show_category(request, cat_slug):
    posts = Posts.objects.filter(cat__slug=cat_slug)

    if len(posts) == 0:
        raise Http404()
    return render(request,'main/category_detail.html',{'posts': posts, 'cat_selected':1})

projectMiWeb/main/templates/main/base.html
{% load static %}
{% load main_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/styles.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  </head>
</head>
<body>
        <a class="btn btn-primary" href="{% url 'home_page' %}">Все предметы</a>
        {% show_categories cat_selected %}

{% block content %}

{% endblock content %}

</body>
</html>

projectMiWeb/main/templates/main/category_detail.html
{% extends 'main/base.html' %}
{% load main_tags %}
{% block title%}Страница с категориями{% endblock title%}

{% block content %}
    {% for post in posts %}
        <div class="post">
            <h3 class="title">{{ post.date_posted }}</h3><br>
                <p class="desc">
                    {{ post.description }}
                </p>
        </div>
    {% endfor %}
{% endblock content %}

projectMiWeb/main/templates/main/create.html
{% extends 'main/base.html' %}
 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
{% block content %}
  <form method="post">
    {% csrf_token %}
    {{ form.cat }}
    {{ form.description }}
    {{ form.date_posted }}
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
{% endblock %}

projectMiWeb/main/templates/main/index.html
{% extends 'main/base.html' %}
{% load main_tags %}
{% block title %}Страница с постами{% endblock title %}

{% block content %}
        {% get_posts as posts %}
        {% for post in posts %}
            <div class="post">
                <h3><span class="obj">{{ post.cat }}</span><br>На {{ post.date_posted }}</h3>
                <p>{{ post.description|linebreaks }}</p>
                {% if post.file %}

                    <a href="{{ post.file.url }}">Файл</a>
                {% endif %}
            </div>
        {% endfor %}

{% endblock content %}

projectMiWeb/main/templates/main/list_categories.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'main/css/styles.css' %}">
<div class="nav-scroller__items dragscroll">
  <nav class="nav-scroller__items">
    {% for cat in cats %}
      {% if cat.posts_set.exists %}
                <a class="nav-scroller__item" href="{{ cat.get_absolute_url }}">{{ cat }}</a>
        {% else %}
      {% endif %}
      {% endfor %}
  </nav>
</div>
  <script>
      document.addEventListener('DOMContentLoaded', () => {
  const $navItems = document.querySelector('.nav-scroller__items');
  const $navItemActive = $navItems.querySelector('.nav-scroller__item_active');
  if (!$navItemActive) {
    return;
  }
  const navItemsRect = $navItems.getBoundingClientRect();
  const navItemActiveRect = $navItemActive.getBoundingClientRect();
  const navItemsLeft = navItemActiveRect.left - navItemsRect.left + (navItemActiveRect.width - navItemsRect.width) / 2;
  $navItems.scrollLeft = navItemsLeft;
});

 </script>

projectMiWeb/main/templates/main/post_detail.html
{% extends 'main/base.html' %}
{% block title %}Post detail{% endblock title %}

{% block content %}
    <div class="post">
            <h3 class="title">{{ post.date_posted }}</h3><br>
            {% autoescape on %}
                <p class="desc">
                    {{ post.description}}
                </p>
            {% endautoescape %}
    </div>

{% endblock content %}